### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by apertureless** [m-danish-iqbal/sections-scroll#3]
Pulled in the old version of jquery, pulled in your css and this plugin.
After while scrolling I am getting an error:

Uncaught Error: Syntax error, unrecognized expression: [href=#scrollto-section-2]

**Comment by m-danish-iqbal** [comment]
Can you please mention jquery version that you are using and also if this error is browser specific?

I just did some fixes on this attribute selector's quotes and checked it on 1.7.0 and above it seems to work fine, This plugin will not work on 1.6.0 or below.

Thanks
